let ID: number = 0;
const STORE: object = {
  categories: [
    "Marketing Digital",
    "Manualidades",
    "Ilustración y Dibujo",
    "Lifestyle",
    "Video",
    "Negocios",
    "Fotografía",
    "Diseño",
    "Escritura",
    "Animación & 3D",
  ],
  courses: [
    {
      id: ID++,
      course_name: "Facebook Ads: Domina estrategias avanzadas",
      category_name: "Marketing Digital",
      subcategory_name: "Marketing Digital",
      level: "Avanzado",
      username: "laia.cardona",
      real_price: 65,
      price: 19,
      discount: 71,
      course_score: 5,
      users: 429,
    },
    {
      id: ID++,
      course_name: "Corte y confección: Diseña tu primera prenda",
      category_name: "Manualidades",
      subcategory_name: "Bordado y costura",
      level: "Introductorio",
      username: "lucilagam",
      real_price: 49.97,
      price: 14.99,
      discount: 70,
      course_score: 3.98,
      users: 1299,
    },
    {
      id: ID++,
      course_name: "Técnicas completas de ilustración Kawaii",
      category_name: "Ilustración y Dibujo",
      subcategory_name: "Ilustración Digital",
      level: "Introductorio",
      username: "paula.bugueno",
      real_price: 53,
      price: 14,
      discount: 74,
      course_score: 4.9,
      users: 795,
    },
    {
      id: ID++,
      course_name: "Nutrición saludable: Alimenta una vida mejor",
      category_name: "Lifestyle",
      subcategory_name: "Lifestyle",
      level: "Completo",
      username: "adriana.puente",
      real_price: 49,
      price: 14.99,
      discount: 70,
      course_score: 5,
      users: 2889,
    },
    {
      id: ID++,
      course_name: "Facebook e Instagram Ads: Campañas desde cero",
      category_name: "Marketing Digital",
      subcategory_name: "Marketing Digital",
      level: "Completo",
      username: "javier.arronte",
      real_price: 49.98,
      price: 19.99,
      discount: 60,
      course_score: 5,
      users: 3900,
    },
    {
      id: ID++,
      course_name: "Guión y Dirección para Cine",
      category_name: "Video",
      subcategory_name: "Producción",
      level: "Intermedio",
      username: "delfinajzo",
      real_price: 31,
      price: 14,
      discount: 56,
      course_score: 3.6,
      users: 849,
    },
    {
      id: ID++,
      course_name: "Doblaje de personajes cartoon con Luis Carreño",
      category_name: "Video",
      subcategory_name: "Locución",
      level: "Intermedio",
      username: "luiscarreno1",
      real_price: 65.52,
      price: 19,
      discount: 71,
      course_score: 5,
      users: 142,
    },
    {
      id: ID++,
      course_name: "Trendhunting: Tendencias para la innovación",
      category_name: "Negocios",
      subcategory_name: "Innovación",
      level: "Introductorio",
      username: "catalinamarin",
      real_price: 55.88,
      price: 19,
      discount: 66,
      course_score: 4.7,
      users: 504,
    },
    {
      id: ID++,
      course_name: "Mindfulness y bienestar: Revoluciona tu empresa",
      category_name: "Negocios",
      subcategory_name: "Liderazgo",
      level: "Completo",
      username: "martinreynoso998",
      real_price: 58,
      price: 17,
      discount: 71,
      course_score: 5,
      users: 239,
    },
    {
      id: ID++,
      course_name: "Fotografía de producto y técnicas de iluminación",
      category_name: "Fotografía",
      subcategory_name: "Fundamentos de fotografía",
      level: "Intermedio",
      username: "matias.posti",
      real_price: 49,
      price: 14.99,
      discount: 70,
      course_score: 5,
      users: 2818,
    },
    {
      id: ID++,
      course_name: "Actúa con tu voz: doblaje para personajes",
      category_name: "Video",
      subcategory_name: "Locución",
      level: "Introductorio",
      username: "pattyazan",
      real_price: 65.52,
      price: 19,
      discount: 71,
      course_score: 5,
      users: 7997,
    },
    {
      id: ID++,
      course_name: "Power Manager: Alcanza tus objetivos",
      category_name: "Negocios",
      subcategory_name: "Liderazgo",
      level: "Introductorio",
      username: "miguel.castuera",
      real_price: 55.88,
      price: 19,
      discount: 66,
      course_score: 3.8,
      users: 388,
    },
    {
      id: ID++,
      course_name: "Ideación y creatividad desde cero",
      category_name: "Marketing Digital",
      subcategory_name: "Publicidad",
      level: "Intermedio",
      username: "mauro-azua",
      real_price: 55.88,
      price: 19,
      discount: 66,
      course_score: 5,
      users: 501,
    },
    {
      id: ID++,
      course_name: "Introducción a las metodologías de innovación",
      category_name: "Negocios",
      subcategory_name: "Innovación",
      level: "Introductorio",
      username: "priscila-williams",
      real_price: 63,
      price: 14,
      discount: 78,
      course_score: 5,
      users: 2340,
    },
    {
      id: ID++,
      course_name: "Edición, postproducción y montaje audiovisual",
      category_name: "Video",
      subcategory_name: "Postproducción",
      level: "Completo",
      username: "antonio.gomez",
      real_price: 59,
      price: 14.99,
      discount: 75,
      course_score: 4.53,
      users: 1093,
    },
    {
      id: ID++,
      course_name: "Dirección de Fotografía Avanzada para Cine",
      category_name: "Video",
      subcategory_name: "Producción",
      level: "Avanzado",
      username: "mourino-santiago",
      real_price: 49,
      price: 19.99,
      discount: 60,
      course_score: 5,
      users: 348,
    },
    {
      id: ID++,
      course_name: "Dibujo y pintura: Técnicas contemporáneas",
      category_name: "Ilustración y Dibujo",
      subcategory_name: "Dibujo",
      level: "Intermedio",
      username: "ricardocelma",
      real_price: 49,
      price: 14.99,
      discount: 70,
      course_score: 5,
      users: 1235,
    },
    {
      id: ID++,
      course_name: "Branding e identidad visual para startups",
      category_name: "Diseño",
      subcategory_name: "Branding",
      level: "Intermedio",
      username: "ceciliarodriguezv",
      real_price: 56,
      price: 14,
      discount: 75,
      course_score: 5,
      users: 1588,
    },
    {
      id: ID++,
      course_name: "Postproducción Fine Art avanzada",
      category_name: "Fotografía",
      subcategory_name: "Retoque Fotográfico",
      level: "Avanzado",
      username: "aminadonskaya776",
      real_price: 49,
      price: 14.99,
      discount: 70,
      course_score: 4.5,
      users: 458,
    },
    {
      id: ID++,
      course_name: "Doblaje y actuación de voz con Mario Arvizu",
      category_name: "Video",
      subcategory_name: "Locución",
      level: "Introductorio",
      username: "marvizu",
      real_price: 59,
      price: 14.99,
      discount: 75,
      course_score: 5,
      users: 3948,
    },
    {
      id: ID++,
      course_name: "El arte de la escritura con Majo Moirón",
      category_name: "Escritura",
      subcategory_name: "Escritura",
      level: "Introductorio",
      username: "majomoiron",
      real_price: 59,
      price: 14.99,
      discount: 75,
      course_score: 3.1,
      users: 4859,
    },
    {
      id: ID++,
      course_name: "Excel avanzado para expertos",
      category_name: "Negocios",
      subcategory_name: "Data",
      level: "Avanzado",
      username: "vrodriguez24",
      real_price: 49,
      price: 14.99,
      discount: 70,
      course_score: 5,
      users: 988,
    },
    {
      id: ID++,
      course_name: "Taller de técnicas de negociación",
      category_name: "Negocios",
      subcategory_name: "Ventas",
      level: "Introductorio",
      username: "anabelen.perdigones",
      real_price: 56,
      price: 9,
      discount: 84,
      course_score: 5,
      users: 341,
    },
    {
      id: ID++,
      course_name: "Redacción creativa publicitaria",
      category_name: "Marketing Digital",
      subcategory_name: "Publicidad",
      level: "Introductorio",
      username: "roberto.guerrero",
      real_price: 49,
      price: 19.99,
      discount: 60,
      course_score: 5,
      users: 241,
    },
    {
      id: ID++,
      course_name: "Animação Frame a Frame no Adobe Animate",
      category_name: "Animación & 3D",
      subcategory_name: "Animación 2D",
      level: "Intermedio",
      username: "juliassimas",
      real_price: 53,
      price: 14,
      discount: 74,
      course_score: 5,
      users: 415,
    },
  ],
};

export default STORE;
